2012/11/20 22:44:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('test')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/index.php/test
---
2012/11/20 22:44:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "about".' in C:\xampp\htdocs\frameworks\yii\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CController.php(271): CController->missingAction('about')
#1 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('about')
#2 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('site/about')
#3 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/sim/index.php/site/about
---
2012/11/20 22:52:20 [error] [exception.CDbException] exception 'CDbException' with message 'Table "users" does not have a column named "username".' in C:\xampp\htdocs\frameworks\yii\db\schema\CDbCommandBuilder.php:570
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(1458): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 C:\xampp\htdocs\sim\protected\components\UserIdentity.php(18): CActiveRecord->findByAttributes(Array)
#2 C:\xampp\htdocs\sim\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\frameworks\yii\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\frameworks\yii\validators\CValidator.php(214): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\frameworks\yii\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\sim\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\sim\protected\components\Controller.php(28): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): Controller->filterHttps(Object(CFilterChain))
#13 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('login')
#17 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('site/login')
#18 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/sim/site/login
HTTP_REFERER=https://localhost/sim/site/login
---
2012/11/27 21:33:59 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('username')
#1 C:\xampp\htdocs\sim\protected\views\layouts\sim.php(25): CWebUser->__get('username')
#2 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\frameworks\yii\web\CController.php(785): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\sim\protected\controllers\SiteController.php(32): CController->render('index')
#6 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#7 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/
---
2012/11/27 21:35:13 [error] [php] Object of class CWebUser could not be converted to string (C:\xampp\htdocs\sim\protected\views\layouts\sim.php:25)
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CController.php(785): SiteController->renderFile()
#1 C:\xampp\htdocs\sim\protected\controllers\SiteController.php(32): SiteController->render()
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): SiteController->runAction()
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): SiteController->run()
#8 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#9 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/
in C:\xampp\htdocs\sim\protected\views\layouts\sim.php (25)
in C:\xampp\htdocs\sim\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\sim\index.php (13)
2012/11/27 21:38:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "logout".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('logout')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/logout
---
2012/11/27 22:12:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "s".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('s')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/s
---
2012/11/27 22:14:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "logout".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('logout')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/logout
---
2012/11/28 20:47:35 [error] [exception.CException] exception 'CException' with message 'Property "Users.login" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(144): CComponent->__get('login')
#1 C:\xampp\htdocs\sim\protected\models\Users.php(90): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\sim\protected\views\users\admin.php(45): Users->search()
#3 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(783): CController->renderPartial('admin', Array, true)
#7 C:\xampp\htdocs\sim\protected\controllers\UsersController.php(135): CController->render('admin', Array)
#8 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): UsersController->actionAdmin()
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#12 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#16 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('admin')
#18 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('users/admin')
#19 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sim/users/admin
HTTP_REFERER=https://localhost/sim/users/
---
2012/11/28 20:47:48 [error] [exception.CException] exception 'CException' with message 'Property "Users.login" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(144): CComponent->__get('login')
#1 C:\xampp\htdocs\sim\protected\models\Users.php(90): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\sim\protected\views\users\admin.php(45): Users->search()
#3 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(783): CController->renderPartial('admin', Array, true)
#7 C:\xampp\htdocs\sim\protected\controllers\UsersController.php(135): CController->render('admin', Array)
#8 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): UsersController->actionAdmin()
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#12 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#16 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('admin')
#18 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('users/admin')
#19 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#20 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/sim/users/admin
HTTP_REFERER=https://localhost/sim/users/create
---
2012/11/28 20:53:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('index')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/index
---
2012/11/28 21:18:27 [error] [exception.CException] exception 'CException' with message 'CWebUser and its behaviors do not have a method or closure named "hashPassword".' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\sim\protected\models\Users.php(103): CComponent->__call('hashPassword', Array)
#1 C:\xampp\htdocs\sim\protected\models\Users.php(103): CWebUser->hashPassword('wwwww')
#2 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(1011): Users->beforeSave()
#3 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(796): CActiveRecord->insert(NULL)
#4 C:\xampp\htdocs\sim\protected\controllers\UsersController.php(65): CActiveRecord->save()
#5 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): UsersController->actionCreate()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#13 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('create')
#15 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('users/create')
#16 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#17 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/sim/users/create
HTTP_REFERER=https://localhost/sim/users/create
---
2012/11/28 21:33:11 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`unit_id`, `username`, `password`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\sim\protected\controllers\UsersController.php (65)
in C:\xampp\htdocs\sim\index.php (13)
2012/11/28 21:33:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`unit_id`, `username`, `password`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\frameworks\yii\db\CDbCommand.php:354
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(1017): CDbCommand->execute()
#1 C:\xampp\htdocs\frameworks\yii\db\ar\CActiveRecord.php(796): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\sim\protected\controllers\UsersController.php(65): CActiveRecord->save()
#3 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): UsersController->actionCreate()
#4 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#11 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('create')
#13 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('users/create')
#14 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/sim/users/create
HTTP_REFERER=https://localhost/sim/users/create
---
2012/11/28 21:36:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\frameworks\yii\web\auth\CAccessControlFilter.php:170
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#8 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('users')
#9 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/sim/users
HTTP_REFERER=https://localhost/sim/login
---
2012/12/04 21:46:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/window_bar_bg".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('images/window_b...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/images/window_bar_bg
HTTP_REFERER=https://localhost/sim/css/sim.css
---
2012/12/04 21:46:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/window_bar_bg".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('images/window_b...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/images/window_bar_bg
HTTP_REFERER=https://localhost/sim/css/sim.css
---
2012/12/04 21:46:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/window_bar_bg".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('images/window_b...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/images/window_bar_bg
---
2012/12/04 21:47:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/window_bar_bg.png".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('images/window_b...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/images/window_bar_bg.png
HTTP_REFERER=https://localhost/sim/css/sim.css
---
2012/12/04 21:47:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/window_bar_bg.png".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('images/window_b...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/images/window_bar_bg.png
---
2012/12/04 22:19:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "collection_points".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collection_poin...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/collection_points
HTTP_REFERER=https://localhost/sim/
---
2012/12/04 22:20:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "collection_points".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collection_poin...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/collection_points
HTTP_REFERER=https://localhost/sim/
---
2012/12/04 22:20:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "collection_points".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collection_poin...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/collection_points
HTTP_REFERER=https://localhost/sim/
---
2012/12/04 22:20:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "collection_points".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collection_poin...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/collection_points
HTTP_REFERER=https://localhost/sim/
---
2012/12/04 22:20:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "collection_points".' in C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collection_poin...')
#1 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/sim/collection_points
HTTP_REFERER=https://localhost/sim/
---
2012/12/04 22:44:17 [error] [php] array_map(): Argument #2 should be an array (C:\xampp\htdocs\frameworks\yii\web\auth\CAccessControlFilter.php:103)
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): ObjectsController->filterAccessControl()
#1 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): ObjectsController->runActionWithFilters()
#4 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): ObjectsController->run()
#5 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#6 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#7 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/objects
in C:\xampp\htdocs\sim\index.php (13)
2012/12/05 07:45:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\frameworks\yii\web\auth\CAccessControlFilter.php:170
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('admin')
#8 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#9 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/sim/collectionpoints/admin
HTTP_REFERER=https://localhost/sim/collectionpoints
---
2012/12/05 08:26:46 [error] [php] include(Object.php): failed to open stream: No such file or directory (C:\xampp\htdocs\frameworks\yii\YiiBase.php:423)
Stack trace:
#0 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): spl_autoload_call()
#1 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CollectionPointsController->runAction()
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CollectionPointsController->filterAccessControl()
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#8 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CollectionPointsController->runActionWithFilters()
#10 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CollectionPointsController->run()
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#12 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#13 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/collectionpoints
in C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php (122)
in C:\xampp\htdocs\sim\index.php (13)
2012/12/05 08:26:57 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/login
---
2012/12/05 08:27:54 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/index.php
---
2012/12/05 08:56:49 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/login
---
2012/12/05 08:57:58 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/login
---
2012/12/05 08:59:10 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php:122)
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CollectionPointsController->runAction()
#1 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CollectionPointsController->filterAccessControl()
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CollectionPointsController->runActionWithFilters()
#7 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CollectionPointsController->run()
#8 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#9 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/collectionpoints
in C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php (122)
in C:\xampp\htdocs\sim\index.php (13)
2012/12/05 08:59:44 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/login
---
2012/12/05 09:05:41 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/login
---
2012/12/05 09:10:01 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
2012/12/05 09:13:05 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\components\WebUser.php(10): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): WebUser->__get('unit_id')
#3 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#4 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#11 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#14 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
2012/12/05 09:20:41 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
2012/12/05 09:22:16 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
2012/12/05 09:22:43 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
2012/12/05 09:26:40 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.unit_id" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('unit_id')
#1 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(122): CWebUser->__get('unit_id')
#2 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#3 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#13 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
2012/12/05 09:27:18 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php:122)
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CollectionPointsController->runAction()
#1 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CollectionPointsController->filterAccessControl()
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CollectionPointsController->runActionWithFilters()
#7 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CollectionPointsController->run()
#8 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#9 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/collectionpoints
in C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php (122)
in C:\xampp\htdocs\sim\index.php (13)
2012/12/05 09:32:03 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php:122)
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CollectionPointsController->runAction()
#1 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#2 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CollectionPointsController->filterAccessControl()
#4 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#6 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CollectionPointsController->runActionWithFilters()
#7 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CollectionPointsController->run()
#8 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#9 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/collectionpoints
in C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php (122)
in C:\xampp\htdocs\sim\index.php (13)
2012/12/05 09:36:12 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\sim\protected\views\collectionPoints\index.php:14)
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\CController.php(870): CollectionPointsController->renderFile()
#1 C:\xampp\htdocs\frameworks\yii\web\CController.php(783): CollectionPointsController->renderPartial()
#2 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(126): CollectionPointsController->render()
#3 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#4 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CollectionPointsController->runAction()
#6 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CollectionPointsController->filterAccessControl()
#9 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#10 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#11 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CollectionPointsController->runActionWithFilters()
#12 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CollectionPointsController->run()
#13 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController()
#14 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\sim\index.php(13): CWebApplication->run()
REQUEST_URI=/sim/collectionpoints
in C:\xampp\htdocs\sim\protected\views\collectionPoints\index.php (14)
in C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php (126)
in C:\xampp\htdocs\sim\index.php (13)
2012/12/05 09:36:55 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.getModel" is not defined.' in C:\xampp\htdocs\frameworks\yii\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\frameworks\yii\web\auth\CWebUser.php(141): CComponent->__get('getModel')
#1 C:\xampp\htdocs\sim\protected\views\collectionPoints\index.php(14): CWebUser->__get('getModel')
#2 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\frameworks\yii\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\frameworks\yii\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\frameworks\yii\web\CController.php(783): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\sim\protected\controllers\CollectionPointsController.php(126): CController->render('index', Array)
#7 C:\xampp\htdocs\frameworks\yii\web\actions\CInlineAction.php(50): CollectionPointsController->actionIndex()
#8 C:\xampp\htdocs\frameworks\yii\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\frameworks\yii\web\filters\CFilter.php(41): CFilterChain->run()
#11 C:\xampp\htdocs\frameworks\yii\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\frameworks\yii\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\frameworks\yii\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\frameworks\yii\web\CController.php(292): CFilterChain->run()
#15 C:\xampp\htdocs\frameworks\yii\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\frameworks\yii\web\CWebApplication.php(142): CWebApplication->runController('collectionpoint...')
#18 C:\xampp\htdocs\frameworks\yii\base\CApplication.php(162): CWebApplication->processRequest()
#19 C:\xampp\htdocs\sim\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/sim/collectionpoints
HTTP_REFERER=https://localhost/sim/
---
